# Generated by Django 3.1.2 on 2020-10-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('profiles', '0002_auto_20201021_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='read',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Blog'),
        ),
    ]
