# Generated by Django 3.1.2 on 2020-10-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201022_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptions',
            old_name='subscriber',
            new_name='user',
        ),
    ]
