# Generated by Django 3.1.2 on 2020-10-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201022_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='blogs',
            field=models.ManyToManyField(blank=True, related_name='subscribed_blogs', to='blog.Blog'),
        ),
    ]
