# Generated by Django 3.1.2 on 2020-10-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201022_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadPosts',
        ),
    ]
