# Generated by Django 3.1.2 on 2020-10-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_delete_readposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='owner',
            new_name='author',
        ),
    ]
